title: 'Yoshifumi Hanada'
description: "A coder's blog"
baseurl: "/blog"
url: "https://nonotoy.github.io"

header_pages:
  - index.md
  - about.md
  - contact.md

style: dark

footer: '<a href="https://www.linkedin.com/in/yoshifumi-hanada/">linkedin</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
